/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SmsMarketingPolicyRouteImport } from './routes/sms-marketing-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ReviewsubmitRouteImport } from './routes/reviewsubmit'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HbeRouteImport } from './routes/hbe'
import { Route as FindRouteImport } from './routes/find'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventSignupRouteImport } from './routes/event-signup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgeVerificationPolicyRouteImport } from './routes/age-verification-policy'
import { Route as AccessibilityStatementRouteImport } from './routes/accessibility-statement'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as ApiPublicWholesaleHubspotRouteImport } from './routes/api/public/wholesale-hubspot'
import { Route as ApiPublicSpinWheelKlaviyoRouteImport } from './routes/api/public/spin-wheel-klaviyo'
import { Route as ApiPublicSpinWheelHubspotRouteImport } from './routes/api/public/spin-wheel-hubspot'
import { Route as ApiPublicReviewRouteImport } from './routes/api/public/review'
import { Route as ApiPublicNewsletterKlaviyoRouteImport } from './routes/api/public/newsletter-klaviyo'
import { Route as ApiPublicNewsletterHubspotRouteImport } from './routes/api/public/newsletter-hubspot'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'
import { Route as ApiPublicEventSignupRouteImport } from './routes/api/public/event-signup'
import { Route as ApiPublicDealClaimRouteImport } from './routes/api/public/deal-claim'
import { Route as ApiPublicContactHubspotRouteImport } from './routes/api/public/contact-hubspot'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsMarketingPolicyRoute = SmsMarketingPolicyRouteImport.update({
  id: '/sms-marketing-policy',
  path: '/sms-marketing-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsubmitRoute = ReviewsubmitRouteImport.update({
  id: '/reviewsubmit',
  path: '/reviewsubmit',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HbeRoute = HbeRouteImport.update({
  id: '/hbe',
  path: '/hbe',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSignupRoute = EventSignupRouteImport.update({
  id: '/event-signup',
  path: '/event-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeVerificationPolicyRoute = AgeVerificationPolicyRouteImport.update({
  id: '/age-verification-policy',
  path: '/age-verification-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityStatementRoute = AccessibilityStatementRouteImport.update({
  id: '/accessibility-statement',
  path: '/accessibility-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWholesaleHubspotRoute =
  ApiPublicWholesaleHubspotRouteImport.update({
    id: '/api/public/wholesale-hubspot',
    path: '/api/public/wholesale-hubspot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSpinWheelKlaviyoRoute =
  ApiPublicSpinWheelKlaviyoRouteImport.update({
    id: '/api/public/spin-wheel-klaviyo',
    path: '/api/public/spin-wheel-klaviyo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSpinWheelHubspotRoute =
  ApiPublicSpinWheelHubspotRouteImport.update({
    id: '/api/public/spin-wheel-hubspot',
    path: '/api/public/spin-wheel-hubspot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReviewRoute = ApiPublicReviewRouteImport.update({
  id: '/api/public/review',
  path: '/api/public/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterKlaviyoRoute =
  ApiPublicNewsletterKlaviyoRouteImport.update({
    id: '/api/public/newsletter-klaviyo',
    path: '/api/public/newsletter-klaviyo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterHubspotRoute =
  ApiPublicNewsletterHubspotRouteImport.update({
    id: '/api/public/newsletter-hubspot',
    path: '/api/public/newsletter-hubspot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventSignupRoute = ApiPublicEventSignupRouteImport.update({
  id: '/api/public/event-signup',
  path: '/api/public/event-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDealClaimRoute = ApiPublicDealClaimRouteImport.update({
  id: '/api/public/deal-claim',
  path: '/api/public/deal-claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactHubspotRoute = ApiPublicContactHubspotRouteImport.update({
  id: '/api/public/contact-hubspot',
  path: '/api/public/contact-hubspot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reviewsubmit': typeof ReviewsubmitRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wholesale': typeof WholesaleRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/contact-hubspot': typeof ApiPublicContactHubspotRoute
  '/api/public/deal-claim': typeof ApiPublicDealClaimRoute
  '/api/public/event-signup': typeof ApiPublicEventSignupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/newsletter-hubspot': typeof ApiPublicNewsletterHubspotRoute
  '/api/public/newsletter-klaviyo': typeof ApiPublicNewsletterKlaviyoRoute
  '/api/public/review': typeof ApiPublicReviewRoute
  '/api/public/spin-wheel-hubspot': typeof ApiPublicSpinWheelHubspotRoute
  '/api/public/spin-wheel-klaviyo': typeof ApiPublicSpinWheelKlaviyoRoute
  '/api/public/wholesale-hubspot': typeof ApiPublicWholesaleHubspotRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reviewsubmit': typeof ReviewsubmitRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wholesale': typeof WholesaleRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/contact-hubspot': typeof ApiPublicContactHubspotRoute
  '/api/public/deal-claim': typeof ApiPublicDealClaimRoute
  '/api/public/event-signup': typeof ApiPublicEventSignupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/newsletter-hubspot': typeof ApiPublicNewsletterHubspotRoute
  '/api/public/newsletter-klaviyo': typeof ApiPublicNewsletterKlaviyoRoute
  '/api/public/review': typeof ApiPublicReviewRoute
  '/api/public/spin-wheel-hubspot': typeof ApiPublicSpinWheelHubspotRoute
  '/api/public/spin-wheel-klaviyo': typeof ApiPublicSpinWheelKlaviyoRoute
  '/api/public/wholesale-hubspot': typeof ApiPublicWholesaleHubspotRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reviewsubmit': typeof ReviewsubmitRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wholesale': typeof WholesaleRoute
  '/products_/$slug': typeof ProductsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/contact-hubspot': typeof ApiPublicContactHubspotRoute
  '/api/public/deal-claim': typeof ApiPublicDealClaimRoute
  '/api/public/event-signup': typeof ApiPublicEventSignupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/newsletter-hubspot': typeof ApiPublicNewsletterHubspotRoute
  '/api/public/newsletter-klaviyo': typeof ApiPublicNewsletterKlaviyoRoute
  '/api/public/review': typeof ApiPublicReviewRoute
  '/api/public/spin-wheel-hubspot': typeof ApiPublicSpinWheelHubspotRoute
  '/api/public/spin-wheel-klaviyo': typeof ApiPublicSpinWheelKlaviyoRoute
  '/api/public/wholesale-hubspot': typeof ApiPublicWholesaleHubspotRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/reviewsubmit'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/wholesale'
    | '/products/$slug'
    | '/api/public/contact'
    | '/api/public/contact-hubspot'
    | '/api/public/deal-claim'
    | '/api/public/event-signup'
    | '/api/public/newsletter'
    | '/api/public/newsletter-hubspot'
    | '/api/public/newsletter-klaviyo'
    | '/api/public/review'
    | '/api/public/spin-wheel-hubspot'
    | '/api/public/spin-wheel-klaviyo'
    | '/api/public/wholesale-hubspot'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/reviewsubmit'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/wholesale'
    | '/products/$slug'
    | '/api/public/contact'
    | '/api/public/contact-hubspot'
    | '/api/public/deal-claim'
    | '/api/public/event-signup'
    | '/api/public/newsletter'
    | '/api/public/newsletter-hubspot'
    | '/api/public/newsletter-klaviyo'
    | '/api/public/review'
    | '/api/public/spin-wheel-hubspot'
    | '/api/public/spin-wheel-klaviyo'
    | '/api/public/wholesale-hubspot'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/reviewsubmit'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/wholesale'
    | '/products_/$slug'
    | '/api/public/contact'
    | '/api/public/contact-hubspot'
    | '/api/public/deal-claim'
    | '/api/public/event-signup'
    | '/api/public/newsletter'
    | '/api/public/newsletter-hubspot'
    | '/api/public/newsletter-klaviyo'
    | '/api/public/review'
    | '/api/public/spin-wheel-hubspot'
    | '/api/public/spin-wheel-klaviyo'
    | '/api/public/wholesale-hubspot'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityStatementRoute: typeof AccessibilityStatementRoute
  AgeVerificationPolicyRoute: typeof AgeVerificationPolicyRoute
  ContactRoute: typeof ContactRoute
  EventSignupRoute: typeof EventSignupRoute
  FaqRoute: typeof FaqRoute
  FindRoute: typeof FindRoute
  HbeRoute: typeof HbeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReviewsubmitRoute: typeof ReviewsubmitRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmsMarketingPolicyRoute: typeof SmsMarketingPolicyRoute
  SocialRoute: typeof SocialRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WholesaleRoute: typeof WholesaleRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicContactHubspotRoute: typeof ApiPublicContactHubspotRoute
  ApiPublicDealClaimRoute: typeof ApiPublicDealClaimRoute
  ApiPublicEventSignupRoute: typeof ApiPublicEventSignupRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRoute
  ApiPublicNewsletterHubspotRoute: typeof ApiPublicNewsletterHubspotRoute
  ApiPublicNewsletterKlaviyoRoute: typeof ApiPublicNewsletterKlaviyoRoute
  ApiPublicReviewRoute: typeof ApiPublicReviewRoute
  ApiPublicSpinWheelHubspotRoute: typeof ApiPublicSpinWheelHubspotRoute
  ApiPublicSpinWheelKlaviyoRoute: typeof ApiPublicSpinWheelKlaviyoRoute
  ApiPublicWholesaleHubspotRoute: typeof ApiPublicWholesaleHubspotRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-marketing-policy': {
      id: '/sms-marketing-policy'
      path: '/sms-marketing-policy'
      fullPath: '/sms-marketing-policy'
      preLoaderRoute: typeof SmsMarketingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewsubmit': {
      id: '/reviewsubmit'
      path: '/reviewsubmit'
      fullPath: '/reviewsubmit'
      preLoaderRoute: typeof ReviewsubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hbe': {
      id: '/hbe'
      path: '/hbe'
      fullPath: '/hbe'
      preLoaderRoute: typeof HbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-signup': {
      id: '/event-signup'
      path: '/event-signup'
      fullPath: '/event-signup'
      preLoaderRoute: typeof EventSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-verification-policy': {
      id: '/age-verification-policy'
      path: '/age-verification-policy'
      fullPath: '/age-verification-policy'
      preLoaderRoute: typeof AgeVerificationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-statement': {
      id: '/accessibility-statement'
      path: '/accessibility-statement'
      fullPath: '/accessibility-statement'
      preLoaderRoute: typeof AccessibilityStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wholesale-hubspot': {
      id: '/api/public/wholesale-hubspot'
      path: '/api/public/wholesale-hubspot'
      fullPath: '/api/public/wholesale-hubspot'
      preLoaderRoute: typeof ApiPublicWholesaleHubspotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spin-wheel-klaviyo': {
      id: '/api/public/spin-wheel-klaviyo'
      path: '/api/public/spin-wheel-klaviyo'
      fullPath: '/api/public/spin-wheel-klaviyo'
      preLoaderRoute: typeof ApiPublicSpinWheelKlaviyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spin-wheel-hubspot': {
      id: '/api/public/spin-wheel-hubspot'
      path: '/api/public/spin-wheel-hubspot'
      fullPath: '/api/public/spin-wheel-hubspot'
      preLoaderRoute: typeof ApiPublicSpinWheelHubspotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/review': {
      id: '/api/public/review'
      path: '/api/public/review'
      fullPath: '/api/public/review'
      preLoaderRoute: typeof ApiPublicReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-klaviyo': {
      id: '/api/public/newsletter-klaviyo'
      path: '/api/public/newsletter-klaviyo'
      fullPath: '/api/public/newsletter-klaviyo'
      preLoaderRoute: typeof ApiPublicNewsletterKlaviyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-hubspot': {
      id: '/api/public/newsletter-hubspot'
      path: '/api/public/newsletter-hubspot'
      fullPath: '/api/public/newsletter-hubspot'
      preLoaderRoute: typeof ApiPublicNewsletterHubspotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event-signup': {
      id: '/api/public/event-signup'
      path: '/api/public/event-signup'
      fullPath: '/api/public/event-signup'
      preLoaderRoute: typeof ApiPublicEventSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deal-claim': {
      id: '/api/public/deal-claim'
      path: '/api/public/deal-claim'
      fullPath: '/api/public/deal-claim'
      preLoaderRoute: typeof ApiPublicDealClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-hubspot': {
      id: '/api/public/contact-hubspot'
      path: '/api/public/contact-hubspot'
      fullPath: '/api/public/contact-hubspot'
      preLoaderRoute: typeof ApiPublicContactHubspotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityStatementRoute: AccessibilityStatementRoute,
  AgeVerificationPolicyRoute: AgeVerificationPolicyRoute,
  ContactRoute: ContactRoute,
  EventSignupRoute: EventSignupRoute,
  FaqRoute: FaqRoute,
  FindRoute: FindRoute,
  HbeRoute: HbeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReviewsubmitRoute: ReviewsubmitRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmsMarketingPolicyRoute: SmsMarketingPolicyRoute,
  SocialRoute: SocialRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WholesaleRoute: WholesaleRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicContactHubspotRoute: ApiPublicContactHubspotRoute,
  ApiPublicDealClaimRoute: ApiPublicDealClaimRoute,
  ApiPublicEventSignupRoute: ApiPublicEventSignupRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRoute,
  ApiPublicNewsletterHubspotRoute: ApiPublicNewsletterHubspotRoute,
  ApiPublicNewsletterKlaviyoRoute: ApiPublicNewsletterKlaviyoRoute,
  ApiPublicReviewRoute: ApiPublicReviewRoute,
  ApiPublicSpinWheelHubspotRoute: ApiPublicSpinWheelHubspotRoute,
  ApiPublicSpinWheelKlaviyoRoute: ApiPublicSpinWheelKlaviyoRoute,
  ApiPublicWholesaleHubspotRoute: ApiPublicWholesaleHubspotRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
